### ISSUE TITLE
No plugin found for prefix 'k8s' in the current project

### ISSUE THREAD

**Issue by burrsutter** [jshiftio/jshift-quickstarts#11]
git clone https://github.com/jshiftio/jshift-quickstarts/
cd jshift-quickstarts/spring-boot
mvn clean k8s:resource -Pkubernetes

No plugin found for prefix 'k8s' in the current project

**Comment by rohanKanojia** [comment]
I think you're facing this because plugin version is set to 0.1-SNAPSHOT. we need to modify all the projects to 0.1.0 instead.

**Comment by burrsutter** [comment]
0.1.0 does make a big difference :-)

**Comment by rohanKanojia** [comment]
@burrsutter : bdw, we are going to migrate these projects again under eclipse org. Right now we're under the process of getting absorbed into eclipse org.
